version: '3.8'

services:
  backend:
    build: ./springboot/app
    ports:
      - "8080:8080"
    networks:
      - app-network

  frontend:
    build: ./angular-app
    ports:
      - "4200:4200"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
