name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v3

      - name: Se connecter à Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image backend
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/mon-backend:latest ./backend

      - name: Build image frontend
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/mon-frontend:latest ./frontend

      - name: Push backend
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/mon-backend:latest

      - name: Push frontend
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/mon-frontend:latest

      - name: Tester avec Docker Compose
        run: |
          docker-compose up -d
          sleep 10
          docker-compose ps
